models/class.py
class Course:

    def __init__(self, title, description, date, duration, max_num_students, id = None):
        self.title = title
        self.description = description
        self.date = date
        self.duration = duration
        self.max_num_students = max_num_students
        self.id = id

models/course.py
class Course:
    def __init__(self, title, description, date, duration, max_num_students, teacher_name = None, id = None):
        self.title = title
        self.description = description
        self.date = date
        self.duration = duration
        self.max_num_students = max_num_students
        self.teacher_name = teacher_name
        self.id = id

models/registration.py
class Registration:
    
    def __init__(self, course, student, id = None):
        self.course = course
        self.student = student
        self.id = id

models/student.py
class Student: 

    def __init__(self, name, dob, experience, email, phone, membership, id = None):
        self.name = name
        self.dob = dob
        self.experience = experience
        self.email = email
        self.phone = phone
        self.membership = membership
        self.id = id

app.py
from flask import Flask, render_template

from controllers.course_controller import courses_blueprint
from controllers.student_controller import student_blueprint
from controllers.registration_controller import registration_blueprint

app = Flask(__name__)

app.register_blueprint(courses_blueprint)
app.register_blueprint(student_blueprint)
app.register_blueprint(registration_blueprint)

@app.route("/")
def home():
    return render_template('index.html')

if __name__ == '__main__':
    app.run()

controllers/course_controller.py
from flask import Blueprint, Flask, redirect, render_template, request

from models.course import Course
import repositories.course_repository as course_repository
import repositories.registration_repository as registration_repository
courses_blueprint = Blueprint("courses", __name__)

@courses_blueprint.route("/courses")
def list_courses():
    courses = course_repository.select_all()
    return render_template ("courses/index.html", courses = courses)

@courses_blueprint.route("/courses/new")
def new_course():
    return render_template("courses/new.html")

@courses_blueprint.route("/courses", methods =["POST"])
def create_course():
    title = request.form["title"]
    description = request.form ["description"]
    date = request.form["date"]
    duration = request.form["duration"]
    max_num_students = request.form["max_num_students"]
    teacher_name = request.form["teacher_name"]

    course = Course(title, description, date, duration, max_num_students, teacher_name)

    course_repository.save(course)

    return redirect(f"/courses/{course.id}")

@courses_blueprint.route("/courses/<id>")
def show(id):
    course = course_repository.select(id)
    students = registration_repository.select_students(id)
    return render_template("courses/show.html", course=course, students=students)

@courses_blueprint.route("/courses/<id>/edit")
def edit_course(id):
    course = course_repository.select(id)
    return render_template('courses/edit.html', course=course)

@courses_blueprint.route("/courses/<id>", methods=["POST"])
def update_course(id):
    title = request.form["title"]
    description = request.form ["description"]
    date = request.form["date"]
    duration = request.form["duration"]
    max_num_students = request.form["max_num_students"]
    teacher_name = request.form["teacher_name"]

    course_to_update = Course(title, description, date, duration, max_num_students, teacher_name, id)
    course_repository.update(course_to_update)
    return redirect(f"/courses/{course_to_update.id}")

@courses_blueprint.route("/courses/<id>/delete", methods=["POST"])
def delete_course(id):
    course_repository.delete(id)
    return redirect("/courses")

controllers/registration_controller.py
from flask import Blueprint, Flask, redirect, render_template, request

from models.student import Student
from models.course import Course
from models.registration import Registration

import repositories.student_repository as student_repository
import repositories.course_repository as course_repository
import repositories.registration_repository as registration_repository

registration_blueprint = Blueprint('registration', __name__)

@registration_blueprint.route("/registrations")
def list_registrations():
    registrations = registration_repository.select_all()
    return render_template('registrations/index.html', registrations = registrations)

@registration_blueprint.route("/registrations/new")
def new_registration():
    students = student_repository.select_all()
    courses = course_repository.select_all()
    return render_template('registrations/new.html', students=students, courses=courses )


@registration_blueprint.route("/registrations", methods=["POST"])
def create_registration():
    course_id = request.form["course_id"]
    student_id = request.form["student_id"]

    course = course_repository.select(course_id)
    student= student_repository.select(student_id)

    new_registration = Registration(course, student)
    registration_repository.save(new_registration)
    return redirect("/registrations")


@registration_blueprint.route("/registrations/<id>/delete", methods= ["POST"])
def delete_registration(id):
    registration_repository.delete(id)
    return redirect("/registrations")


@registration_blueprint.route("/registrations/<id>/edit")
def edit_registration(id):
    students = student_repository.select_all()
    courses = course_repository.select_all()
    registration = registration_repository.select(id)
    return render_template('registrations/edit.html', registration= registration, students=students, courses=courses )


@registration_blueprint.route("/registrations/<id>", methods=["POST"])
def update_registration(id):
    course_id = request.form["course_id"]
    student_id = request.form["student_id"]

    course = course_repository.select(course_id)
    student= student_repository.select(student_id)

    registration_to_update = Registration(course, student, id)
    registration_repository.update(registration_to_update)
    return redirect("/registrations")

controllers/student_controller.py
from flask import Blueprint, Flask, redirect, render_template, request

from models.student import Student
from models.registration import Registration

import repositories.student_repository as student_repository
import repositories.course_repository as course_repository
import repositories.registration_repository as registration_repository

student_blueprint = Blueprint("students", __name__)

@student_blueprint.route("/students")
def list_students():
    students = student_repository.select_all()
    return render_template ("students/index.html", students = students)

@student_blueprint.route("/students/new")
def new_student():
    courses = course_repository.select_all()
    return render_template("students/new.html", courses= courses)

@student_blueprint.route("/students", methods=["POST"])
def create_student():
    name = request.form["name"]
    dob = request.form["dob"]
    experience = request.form["experience"]
    email = request.form["email"]
    phone = request.form['phone']
    membership= request.form["membership"]
    course_id = request.form["course_id"]

    course = course_repository.select(course_id)
    new_student = Student(name, dob, experience, email, phone, membership)
    new_registration = Registration(course, new_student)

    student_repository.save(new_student)
    registration_repository.save(new_registration)
    return redirect(f"/students/{new_student.id}")

@student_blueprint.route("/students/<id>")
def show(id):
    student = student_repository.select(id)
    courses = registration_repository.select_courses(id)
    return render_template("students/show.html", student=student, courses= courses)

@student_blueprint.route("/students/<id>/delete", methods=["POST"])
def delete_student(id):
    student_repository.delete(id)
    return redirect("/students")

@student_blueprint.route("/students/<id>/edit")
def edit_student(id):
    student = student_repository.select(id)
    return render_template('students/edit.html', student= student)

@student_blueprint.route("/students/<id>", methods=["POST"])
def update_student(id):
    name = request.form["name"]
    dob = request.form["dob"]
    experience = request.form["experience"]
    email = request.form["email"]
    phone = request.form['phone']
    membership= request.form["membership"]

    student_to_update = Student(name, dob, experience, email, phone, membership, id)

    student_repository.update(student_to_update)
    return redirect(f"/students/{student_to_update.id}")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Prata&display=swap" rel="stylesheet">
    <!-- <link rel="stylesheet" href="static/style.css"> -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/tables.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/show_edit.css')}}">

    <title>Mariuca School</title>
</head>
<body>
    <header>
        <div class="menu">
            <div class="title">
                <img src="/static/images/Screenshot 2020-10-07 at 15.02.41.png" alt="logo">
                <h1 id="header_title" >School App</h1>
            </div>
            <nav >
                <ul>
                    <li class="home_button"><a href="{{url_for('home')}}">Home</a></li>
                    <li class="nav_button"><a href="{{ url_for('students.list_students')}}">Students</a></li>
                    <li class="nav_button"><a href="{{ url_for('courses.list_courses')}}">Courses</a></li>
                    <li class="nav_button"><a href="{{ url_for('registration.list_registrations')}}">Registrations</a></li>
                </ul>
            </nav>
        </div>
    </header>
    <main>
        {% block content %}
        {% endblock content %}
    </main>
    <footer>
        <p>The data found in this website is not real and created for academic purposes</p>
    </footer>
</body>
</html>

templates/courses/edit.html
{% extends 'base.html' %}

{% block content %}
<div class="form_add_create_edit">
    <h2>Edit course</h2>

    <form class='form_course' action="/courses/{{course.id}}" method="POST">
        <div class="column_form">
            <label for="title">Course Title:</label>
            <input type="text" id="title" name="title" value='{{course.title}}''>
        </div>
        <div class="column_form">
            <label for="description">Description:</label>
            <textarea id="description" name="description" cols="50" rows="6" value='{{course.description}}'> This stress-busting course will give you an array of options for the festive period and make sure you're ready to go when that time of year comes around. No need to panic anymore but be prepared, they'll have you making Christmas dinner every year for the rest of your life after this course!</textarea>
        </div>
        <div class="column_form">
            <label for="date">Date:</label>
            <input type="text" id="date" name="date" value='{{course.date}}''>
        </div>
        <div class="column_form">
            <label for="duration">Duration:</label>
            <input type="number" id="duration" name="duration" value='{{course.duration}}''>
        </div>
        <div class="column_form">
            <label for="max_num_student">Max, Capacity:</label>
            <input type="number" id="max_num_students" name="max_num_students" value='{{course.max_num_students}}'>
        </div>
        <div class="column_form">
            <label for="teacher_name">Teacher:</label>
            <input type="text" id="teacher_name" name="teacher_name" value='{{course.teacher_name}}'>
        </div>
        <button type="submit">Save changes</button>

    </form>
</div>
    
{% endblock content %}

templates/courses/index.html
{% extends 'base.html' %}
{% block content %}
<section class="index-table home_page">
    <table>
        <thead>
            <tr>
                <th colspan="5">List of Courses</th>
            </tr>
        </thead>
        <tbody>
            <tr class="header_table">
                <td>Course:</td>
                <td>Date:</td>
                <td>Max. Capacity:</td>
                <td>Teacher:</td>
                <td>Availability:</td>
            </tr>
            {% for course in courses %}
            <tr>
                <td>{{course.title}}</td>
                <td>{{course.date}}</td>
                <td>{{course.max_num_students}}</td>
                <td>{{course.teacher_name}}</td>
                <td></td>
                <td class="details"><a href="/courses/{{ course.id}}">More details</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</section>
{% endblock content %}

templates/courses/new.html
{% extends 'base.html' %}
{% block content %}
    <div class="form_add_create_edit">
        <h2>Add a new course</h2>

        <form class='form_course' action="/courses" method="POST">
            <div class= "column_form">
                <label for="title">Course Title:</label>
                <input type="text" id="title" name="title">
            </div>
            <div class= "column_form">
                <label for="description">Description:</label>
                <textarea id="description" name="description" cols="50" rows="8"></textarea>
            </div>
        <div class="duration_date">
            <div class= "column_form">
                <label for="date">Date:</label>
                <input type="text" id="date" name="date" placeholder="Every:">
            </div>
            <div class= "column_form">
                <label for="duration">Duration:</label>
                <input type="number" id="duration" name="duration" placeholder="Number of hours">
            </div>
        </div>
            <div class= "column_form">
                <label for="max_num_student">Max. Capacity:</label>
                <input type="number" id="max_num_students" name="max_num_students">
            </div>
            <div class= "column_form">
                <label for="teacher_name">Teacher Name:</label>
                <input type="text" id="teacher_name" name="teacher_name">
            </div>
            <input type="submit">

        </form>
    </div>
{% endblock content %}

templates/courses/show.html
{% extends 'base.html' %}
{% block content %}
<div class="course_details">
    <h2>{{course.title}}</h2>
    <div id="container_course_details">
        <div class="block_courses">
            <p class="description_details"><b>Description:</b> <br> {{course.description}}</p>
            <div class="max_teacher">
                <p><b>Max. number of students: </b>{{course.max_num_students}}</p>
                <p><b>Teacher: </b>{{course.teacher_name}}</p>
            </div>
            <div class="date_duration_course">
                <p>Every {{course.date}}</p>
                <p>Duration: {{course.duration}}h</p>
            </div>
        </div>
        <ul class="students-courses">
            <b>Students list: </b>
            {% for student in students %}
            <li>{{student.name}}</li>
            {% endfor %}
        </ul>
        <a href="/registrations/new">Add Student</a>
    </div>
    <div class="edit_delete">
        <a class ="edit_course" href="/courses/{{ course.id }}/edit">Edit</a>  
        <form action="/courses/{{ course.id}}/delete" method="POST">
            <input type="submit" value="Delete">
        </form>
    </div>
</div>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="home_page">
    <div class="welcome">
        <q><cite> People who love to eat are always the best people. </q> 
    <figcaption> &mdash; Julia Child  </figcaption>
    </div>
    <div id="index_buttons">
        <div class="student_buttons">
            <button class="index_student_bt"><a href="{{ url_for('students.new_student') }}"> Add Student </a></button>
            <!-- <button class="index_student_bt"><a href="{{ url_for('students.list_students')}}">Student List</a></button> -->
        </div>
        <div class="course_buttons">
            <button class="index_courses_bt"><a href="{{ url_for('courses.new_course') }}">Create Course</a></button>
            <!-- <button class="index_courses_bt"><a href="{{ url_for('courses.list_courses')}}">Upcoming Courses</a></button> -->
        </div>
    </div>
</div>   
{% endblock content %}

templates/students/edit.html
{% extends 'base.html' %}
{% block content %}

    <div class="form_add_create_edit">
        <h2>Edit Student</h2>

        <form action="/students/{{student.id}}" method='POST'>
            <div class="column_form">
                <label for="name">First and Second name of the Student:</label>
                <input type="text" id="name" name="name" value="{{student.name}}">
            </div>
            <div class="column_form">
                <label for="dob">Date of Birth:</label>
                <input type="date" id="dob" name="dob" value="{{student.dob}}">
            </div>
            <div class="column_form">
                <label for="experience">Level:</label>
                <input type="text" id="experience" name="experience" value="{{student.experience}}">
            </div>
            <div class="column_form">
                <label for="email">Email:</label>
                <input type="text" id="email" name="email" value="{{student.email}}">
            </div>
            <div class="column_form">
                <label for="phone">Phone:</label>
                <input type="text" id="phone" name="phone" value="{{student.phone}}">
            </div>
            <div class="column_form">
                <label for="membership">Membership:</label>
                <input type="text" id="membership" name="membership" value="{{student.membership}}">
            </div>
            <input type="submit" value="Save Changes">
        </form>
    </div>
    
{% endblock content %}

templates/students/index.html
{% extends 'base.html' %}

{% block content %}
<section class="index-table home_page">
    <table>
        <thead>
            <tr>
                <th colspan="5">List of Students</th>
            </tr>
        </thead>
        <tbody>
            <tr class="header_table">
                <td>Name:</td>
                <td>DOB:</td>
                <td>Level:</td>
                <td>Email:</td>
                <td>Membership:</td>
            </tr>
            {% for student in students %}
            <tr>
                <td>{{student.name}}</td>
                <td>{{student.dob}}</td>
                <td>{{student.experience}}</td>
                <td>{{student.email}}</td>
                {% if student.membership == True %}
                    <td class="check"><p class="check">&#10003</p></td>
                {% else %}
                    <td><p></p></td>
                {% endif %}
                <td class="details"><a href="/students/{{student.id}}">More details</a></td>
            </tr>
            {% endfor %}
    </tbody>
    </table>
</section>
{% endblock content %}

templates/students/new.html
{% extends 'base.html' %}
{% block content %}
    <div class="form_add_create_edit">
        <h2>Add a New Student</h2>

        <form action="/students" method="POST">
            <div class= "column_form">
                <label for="name">First and Second name of the Student:</label>
                <input type="text" id="name" name="name">
            </div>
            <div class= "column_form">
                <label for="dob">Date of Birth:</label>
                <input type="date" id="dob" name="dob">
            </div>
            <div class= "column_form">
                <label for="email">Email:</label>
                <input type="text" id="email" name="email">
            </div>
            <div class= "column_form">
                <label for="phone">Phone:</label>
                <input type="text" id="phone" name="phone">
            </div>
            <div class= "column_form">
                <label for="membership">Membership:</label>
                <input type="text" id="membership" name="membership">
            </div>
            <div class= "column_form">
                <label for="experience">Level:</label>
                <input type="text" id="experience" name="experience">
            </div>
            <div class= "column_form">
                <label for="course_id">Select Course:</label>
                <select name="course_id" id="course_id" >
                    {% for course in courses %}
                    <option value="{{course.id}}"> {{ course.title }}</option>
                    {% endfor %}
                </select>
            </div>
            <input type="submit" value="Add Student">
        </form>
    </div>
   
{% endblock content %}

templates/students/show.html
{% extends 'base.html' %}
{% block content %}
    
    <div class='student_details'> 
        <h2>{{student.name}}</h2>
        <div id="container_student_details">
            <div class="student_block">
                <p>Level: {{student.experience}}</p>
                <p>Membership: 
                    {% if student.membership == True %} <i>&#10003</i>
                    {% else %}<i> No</i>
                    {% endif %}</p>
                <ul> Contact details:
                    <li> Email: {{student.email}}</li>
                    <li> Phone: {{student.phone}} </li>
                </ul>
                <ul> Personal details:
                    <li>Date of Birth: {{student.dob}} </li>
                </ul>
            </div>
            <ul class= "students-courses">
                Courses enrolled: 
                {% for course in courses %}
                <li>{{course.title}} <a href="{{ url_for('registration.list_registrations')}}">(Change/delete course)</a></li>
                {% endfor %}
            </ul>
        </div>
        <div class="edit_delete">
            <a class="edit_student" href="/students/{{student.id}}/edit">Edit student details</a>
            <form action="/students/{{student.id}}/delete" method="POST">
                <input type="submit" value="Delete Student">
            </form> 
            <a href="/registrations/new">Add Course</a>
        </div>
    </div> 
{% endblock content %}